import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  Award,
  Bell,
  Bot,
  Box,
  Building,
  Calculator,
  Calendar,
  CalendarClock,
  CheckSquare,
  ClipboardCheck,
  Clock,
  Compass,
  Crown,
  Database,
  EyeOff,
  FileCheck,
  FileCode,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  FlaskConical,
  Folder,
  FolderKanban,
  FolderOpen,
  FolderTree,
  GitCompare,
  GitCompareArrows,
  GitFork,
  Globe,
  GraduationCap,
  History,
  Home,
  Inbox,
  Key,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  Library,
  Link,
  List,
  Lock,
  Mail,
  MessageSquare,
  Network,
  Radio,
  Scale,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  Sparkles,
  Store,
  User,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type * as LucideIcons from "lucide-react";

export type LucideIconName = keyof typeof LucideIcons;

/**
 * Explicit registry of the lucide icons referenced by name in tab/modal
 * configs. Runtime lookups must go through this map instead of a
 * `import * as LucideIcons` namespace lookup, which defeats tree-shaking and
 * pulls the entire icon set (~1700 modules) into a shared chunk.
 * Unknown names resolve to undefined — same as a bad name did before.
 */
const lucideIconMap = {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  Award,
  Bell,
  Bot,
  Box,
  Building,
  Calculator,
  Calendar,
  CalendarClock,
  CheckSquare,
  ClipboardCheck,
  Clock,
  Compass,
  Crown,
  Database,
  EyeOff,
  FileCheck,
  FileCode,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  FlaskConical,
  Folder,
  FolderKanban,
  FolderOpen,
  FolderTree,
  GitCompare,
  GitCompareArrows,
  GitFork,
  Globe,
  GraduationCap,
  History,
  Home,
  Inbox,
  Key,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  Library,
  Link,
  List,
  Lock,
  Mail,
  MessageSquare,
  Network,
  Radio,
  Scale,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  Sparkles,
  Store,
  User,
  Users,
  Wallet,
  Zap,
} satisfies Partial<Record<LucideIconName, LucideIcon>>;

export const getLucideIcon = (name: LucideIconName): LucideIcon | undefined =>
  (lucideIconMap as Partial<Record<LucideIconName, LucideIcon>>)[name];
